config/routes.rb
Rails.application.routes.draw do
  resources :companies 
  root 'companies#index' 
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/t201603.rb
class T201603 < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :find_company, only: [:show, :edit, :update, :destroy]
  def index
  	@companies = Company.all.order("created_at DESC")
  end

  def new
  	@company = Company.new
  end

  def create
  	@company = Company.new(company_params)

  	if @company.save
  	  redirect_to @company
  	else
  	  render 'new'
  	end
  end

  def show
  end

  def edit
  end

  def update
    if @company.update(company_params)
      redirect_to @company
    else
      render 'edit'
    end
  end

  def destroy 
    @company.destroy
    redirect_to root_path
  end
  	
  private

  def find_company
  	@company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit( :companies_name, :companies_contact_name, :companies_contact_phone, :companies_contact_email, :companies_domain, :companies_street_address, :companies_city, :companies_state, :companies_zip, :companies_taxable, :companies_billing_rate, :companies_purchase_order, :companies_terms, :companies_report_email1, :companies_report_email2, :companies_report_email3, :companies_report_email4, :companies_report_email5, :companies_report_email6, :companies_report_email7, :companies_report_email8 )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>

<%= f.label :companies_name, 'Company Name' %><br>
<%= f.text_field :companies_name %><br>
<br>
<%= f.label :companies_domain, 'Domain' %><br>
<%= f.text_field :companies_domain %><br>
<br>
<p><strong>Contact Person:</strong></p>
<%= f.label :companies_contact_name, 'Contact Name' %><br>
<%= f.text_field :companies_contact_name %><br>
<br>
<%= f.label :companies_contact_phone, 'Contact Phone' %><br>
<%= f.text_field :companies_contact_phone %><br>
<br>
<%= f.label :companies_contact_email, 'Contact Email' %><br>
<%= f.text_field :companies_contact_email %><br>
<br>
<p><strong>Report Recipients:</strong></p>
<%= f.label :companies_report_email1, 'Email 1' %><br>
<%= f.text_field :companies_report_email1 %><br>
<br>
<%= f.label :companies_report_email2, 'Email 2' %><br>
<%= f.text_field :companies_report_email2 %><br>
<br>
<%= f.label :companies_report_email3, 'Email 3' %><br>
<%= f.text_field :companies_report_email3 %><br>
<br>
<p><strong>Address:</strong></p>
<%= f.label :companies_street_address, 'Street Address' %><br>
<%= f.text_field :companies_street_address %><br>
<br>
<%= f.label :companies_city %><br>
<%= f.text_field :companies_city %><br>
<br>
<%= f.label :companies_state %><br>
<%= f.text_field :companies_state %><br>
<br>
<%= f.label :companies_zip %><br>
<%= f.text_field :companies_zip %><br>
<br>
<p><strong>Billing Details:</strong></p>
<%= f.label :companies_taxable %><br>
<%= f.select :companies_taxable, [['Yes', true], ['No', false]] %><br>
<br>
<%= f.label :companies_billing_rate, 'Billing Rate' %><br>
<%= f.select :companies_billing_rate, [['Standard', 'standard'], ['Custom', 'custom']] %><br>
<br>
<%= f.label :companies_terms %><br>
<%= f.select :companies_terms, [['Net 30', 30], ['Net 60', 60], ['Net 90', 90]] %><br>
<br>
<%= f.label :companies_purchase_order %><br>
<%= f.text_field :companies_purchase_order %><br>
<br>

<%= f.submit %>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>

<%= render 'form' %>

app/views/companies/index.html.erb
<% @companies.each do |company| %>
    <!-- <h2><%= company.title %></h2> -->
    <h2><%= company.companies_name %></h2>

  <%= link_to "View Company ", company %>
<% end %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

app/views/companies/show.html.erb
<h1><%= @company.companies_name %></h1>
<div>
  <p>
    Domain: <%= @company.companies_domain %>
  </p>
  <p><strong>Contact Person:</strong><br>
    Contact Name: <%= @company.companies_contact_name %><br>
  	Contact Phone: <%= @company.companies_contact_phone %><br>
    Contact Email: <%= @company.companies_contact_email %>
  </p>
  <p><strong>Report Recipients:</strong><br>
    Email 1: <%= @company.companies_report_email1 %><br>
    Email 2: <%= @company.companies_report_email2 %><br>
    Email 3: <%= @company.companies_report_email3 %>
  </p>
  <p><strong>Address:</strong><br>
  	<%= @company.companies_street_address %><br>
  	<%= @company.companies_city %>, <%= @company.companies_state %> <%= @company.companies_zip %>
  </p>
  <p><strong>Billing Details:</strong><br>
  	Taxable: <%= @company.companies_taxable %><br>
  	Billing Rate: <%= @company.companies_billing_rate %><br>
    Purchase Order: <%= @company.companies_purchase_order %><br>
  	Terms: <%= @company.companies_terms %>
  </p>
 </div>

<%= link_to "Edit Company", edit_company_path(@company) %>

<%= link_to "Delete Company", company_path(@company), method: :Delete, data: { confirm: "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BillingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
<%= link_to "Home", root_path %>
<%= link_to "New Company", new_company_path %>
  </nav>
<%= yield %>

</body>
</html>